# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
notifications:
  email:
    - faicel.chamroukhi@unicaen.fr
    - florian.lecocq@outlook.com
    - marius.bartcus@gmail.com
