# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IRLS <- function(X, Tau, Gamma, Winit, verbose = FALSE) {
    .Call(`_samurais_IRLS`, X, Tau, Gamma, Winit, verbose)
}

costMatrix <- function(y, X, Lmin = 1) {
    .Call(`_samurais_costMatrix`, y, X, Lmin)
}

forwardsBackwards <- function(prior, transmat, f_tk) {
    .Call(`_samurais_forwardsBackwards`, prior, transmat, f_tk)
}

multinomialLogit <- function(W, X, Y, Gamma) {
    .Call(`_samurais_multinomialLogit`, W, X, Y, Gamma)
}

